### ISSUE TITLE
Reconsider pre-publish strategy?

### ISSUE THREAD

**Issue by hemanth** [pugjs/void-elements#17]
WRT #15 I feel we need to look for a better way of fetching the void-elements and also include more robust tests.

**Comment by ForbesLindesay** [comment]
I don't think any kind of test would have caught this.

One interesting idea: travis lets you automatically make a build run every night.  If we update the test so that it does an `assert.deepEqual(localVersion, versionPublishedToNpm)`, then we could have npm alert us (via a failing build) within 24 hours of an update to the list of void elements.  Allowing us to check the new list looks right and publish a new version.

**Comment by ForbesLindesay** [comment]
I think #18 should resolve this?
